export const GET_BLOGS_LOADING = 'GET_BLOGS_LOADING';
export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS';
export const GET_BLOGS_ERROR = 'GET_BLOGS_ERROR';

export const GET_BLOG_LOADING = 'GET_BLOG_LOADING';
export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS';
export const GET_BLOG_ERROR = 'GET_BLOG_ERROR';

export const ADD_BLOG_LOADING = 'ADD_BLOG_LOADING';
export const ADD_BLOG_SUCCESS = 'ADD_BLOG_SUCCESS';
export const ADD_BLOG_ERROR = 'ADD_BLOG_ERROR';
